/**
 ******************************************************************************
 * @file           : fault_handling.c
 * @project        : Agnikul Generic Software Library
 * @brief          : File containing the functions that ghandle errors.
 * @author         : Shawn N,Dheeraj R
 * @version        : v2.0
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) Agnikul Cosmos Private Limited
 * All rights reserved.</center></h2>
 *
 * ****************************************************************************
 */

#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <signal.h>
#include <errno.h>
#include "fault_handling.h"
#include <execinfo.h>
#include <unistd.h>
#include "ipc.h"

/*******************************************************************************
 * Static Function Prototypes
 ******************************************************************************/
/**
 * @brief   Function prints the backtrace of function calls to help with debugging
 * @details Reference: https://stackoverflow.com/questions/3899870/print-call-stack-in-c-or-c
 * 			https://stackoverflow.com/questions/6934659/how-to-make-backtrace-
 * 			backtrace-symbols-print-the-function-names
 * @param   None
 * @return  None
 *
 * */
static void print_trace(void);

/*******************************************************************************
 * Function definitions
 ******************************************************************************/

/**
 * @brief    Handles errors generated by system calls. Used in the PRINT_ERR macro.
 * @param    Error number
 * @param    String format - This is the same formatting used by stdlib
 * @return   int - 0 on success, -1 on failure
 *
 * */
int handle_err(int err_no, const char *fmt, ...)
{
    #define ERRSTRMAX 512		/**<Size in bytes of error string*/
    char *err_str;				/**<Pointer to error string*/
    va_list argp;

    err_str = malloc(ERRSTRMAX);	/**<Reserve size of max string on heap*/
    if (err_str == NULL)
        return -1;

    va_start(argp, fmt);			/**<Print variable arguments to err_str*/
    vsnprintf(err_str, ERRSTRMAX-1, fmt, argp);
    va_end(argp);

    fprintf(stderr, "%s", err_str);	/**<Print err_str to terminal*/
    if (errno) {
    	fprintf(stderr, " ");				/**<print errno to terminal*/
        fprintf(stderr, "Errno: %d: ", errno);
#ifdef ERR_PRINT_S
        fprintf(stderr, "\n");
#endif
#ifndef ERR_PRINT_S
        perror("Kernel says");	/**<Print statement associated with errno*/
#endif
    }
    printf("\n");
    free(err_str);			/**<Free malloc memory*/
    if (!err_no)
        return 0;

#ifdef ERR_FATAL
    print_trace();
    exit(err_no);
#endif

}

static void print_trace(void) {
    size_t i, size;
    enum Constexpr { MAX_SIZE = 1024 };
    void *array[MAX_SIZE];
    size = backtrace(array, MAX_SIZE);
    backtrace_symbols_fd(array, size, STDOUT_FILENO);
    puts("");
}
